# DO NOT DELETE

build/htserver.o: src/banana.h
build/htserver.o: src/logger.h
build/htserver.o: src/htserver.h
build/htserver.o: src/config.h
build/htserver.o: src/bconfig.h
build/banana.o: src/banana.h
build/banana.o: src/logger.h
build/banana.o: src/htserver.h
build/banana.o: src/config.h
build/banana.o: src/bconfig.h
build/banana.o: src/em.h
build/config.o: src/config.h
build/logger.o: src/logger.h
build/em.o: src/em.h
build/em.o: src/logger.h
