cat <<EOT
///////// THIS IS AUTOGENERATED
///////// LOOK AT TOOLS/gen_pages.sh for more info
/////////
#include "page.h"
#include ".page_defs.h"
#include ".page_defs.h"

void bind_pages() {
EOT
grep -h PAGE $@ | perl -pi -e "s/PAGE\((\w+), (.*)\).*/htserver_bind(htserver, \2, \1);/"
cat <<EOT
}
EOT
